# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mikosz/work/CoconutTools

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mikosz/work/CoconutTools

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mikosz/work/CoconutTools/CMakeFiles /home/mikosz/work/CoconutTools/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mikosz/work/CoconutTools/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CoconutTools_Logger

# Build rule for target.
CoconutTools_Logger: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CoconutTools_Logger
.PHONY : CoconutTools_Logger

# fast build rule for target.
CoconutTools_Logger/fast:
	$(MAKE) -f CMakeFiles/CoconutTools_Logger.dir/build.make CMakeFiles/CoconutTools_Logger.dir/build
.PHONY : CoconutTools_Logger/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named unit-tests

# Build rule for target.
unit-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unit-tests
.PHONY : unit-tests

# fast build rule for target.
unit-tests/fast:
	$(MAKE) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/build
.PHONY : unit-tests/fast

src/main/c++/logger/Logger.o: src/main/c++/logger/Logger.cpp.o
.PHONY : src/main/c++/logger/Logger.o

# target to build an object file
src/main/c++/logger/Logger.cpp.o:
	$(MAKE) -f CMakeFiles/CoconutTools_Logger.dir/build.make CMakeFiles/CoconutTools_Logger.dir/src/main/c++/logger/Logger.cpp.o
.PHONY : src/main/c++/logger/Logger.cpp.o

src/main/c++/logger/Logger.i: src/main/c++/logger/Logger.cpp.i
.PHONY : src/main/c++/logger/Logger.i

# target to preprocess a source file
src/main/c++/logger/Logger.cpp.i:
	$(MAKE) -f CMakeFiles/CoconutTools_Logger.dir/build.make CMakeFiles/CoconutTools_Logger.dir/src/main/c++/logger/Logger.cpp.i
.PHONY : src/main/c++/logger/Logger.cpp.i

src/main/c++/logger/Logger.s: src/main/c++/logger/Logger.cpp.s
.PHONY : src/main/c++/logger/Logger.s

# target to generate assembly for a file
src/main/c++/logger/Logger.cpp.s:
	$(MAKE) -f CMakeFiles/CoconutTools_Logger.dir/build.make CMakeFiles/CoconutTools_Logger.dir/src/main/c++/logger/Logger.cpp.s
.PHONY : src/main/c++/logger/Logger.cpp.s

src/test/c++/logger/Logger.o: src/test/c++/logger/Logger.cpp.o
.PHONY : src/test/c++/logger/Logger.o

# target to build an object file
src/test/c++/logger/Logger.cpp.o:
	$(MAKE) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/test/c++/logger/Logger.cpp.o
.PHONY : src/test/c++/logger/Logger.cpp.o

src/test/c++/logger/Logger.i: src/test/c++/logger/Logger.cpp.i
.PHONY : src/test/c++/logger/Logger.i

# target to preprocess a source file
src/test/c++/logger/Logger.cpp.i:
	$(MAKE) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/test/c++/logger/Logger.cpp.i
.PHONY : src/test/c++/logger/Logger.cpp.i

src/test/c++/logger/Logger.s: src/test/c++/logger/Logger.cpp.s
.PHONY : src/test/c++/logger/Logger.s

# target to generate assembly for a file
src/test/c++/logger/Logger.cpp.s:
	$(MAKE) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/test/c++/logger/Logger.cpp.s
.PHONY : src/test/c++/logger/Logger.cpp.s

src/test/c++/unit-tests.o: src/test/c++/unit-tests.cpp.o
.PHONY : src/test/c++/unit-tests.o

# target to build an object file
src/test/c++/unit-tests.cpp.o:
	$(MAKE) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/test/c++/unit-tests.cpp.o
.PHONY : src/test/c++/unit-tests.cpp.o

src/test/c++/unit-tests.i: src/test/c++/unit-tests.cpp.i
.PHONY : src/test/c++/unit-tests.i

# target to preprocess a source file
src/test/c++/unit-tests.cpp.i:
	$(MAKE) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/test/c++/unit-tests.cpp.i
.PHONY : src/test/c++/unit-tests.cpp.i

src/test/c++/unit-tests.s: src/test/c++/unit-tests.cpp.s
.PHONY : src/test/c++/unit-tests.s

# target to generate assembly for a file
src/test/c++/unit-tests.cpp.s:
	$(MAKE) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/test/c++/unit-tests.cpp.s
.PHONY : src/test/c++/unit-tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... CoconutTools_Logger"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... unit-tests"
	@echo "... src/main/c++/logger/Logger.o"
	@echo "... src/main/c++/logger/Logger.i"
	@echo "... src/main/c++/logger/Logger.s"
	@echo "... src/test/c++/logger/Logger.o"
	@echo "... src/test/c++/logger/Logger.i"
	@echo "... src/test/c++/logger/Logger.s"
	@echo "... src/test/c++/unit-tests.o"
	@echo "... src/test/c++/unit-tests.i"
	@echo "... src/test/c++/unit-tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

