#ifndef _COCONUT_TOOLS_SERIALISATION_MAKESERIALISABLEMACRO_HPP_
#define _COCONUT_TOOLS_SERIALISATION_MAKESERIALISABLEMACRO_HPP_

// TODO: unify macro prefixes (Logger uses CT, Enum and Serialisation use CCN)
#define CCN_MAKE_SERIALISABLE(SERIALISER_TYPE_NAME, SERIALISER_OBJECT_NAME, OBJECT_TYPE_NAME, OBJECT_NAME) \
	template <class SERIALISER_TYPE_NAME> \
	void serialise( \
		SERIALISER_TYPE_NAME& SERIALISER_OBJECT_NAME, \
		typename SERIALISER_TYPE_NAME::template SerialiseArgument<OBJECT_TYPE_NAME> OBJECT_NAME \
		)

#endif /* _COCONUT_TOOLS_SERIALISATION_MAKESERIALISABLEMACRO_HPP_ */
